# Включение поддержки современных библиотек AndroidX и совместимости со старыми
android.useAndroidX=true
android.enableJetifier=true

# Выделение достаточного объема оперативной памяти для сборщика Gradle (2 ГБ)
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

# Включение оптимизации, фонового режима и кэширования для стабильности
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
